export const SALON_SERVICES = [
  {
    id: 1,
    category: "Facial",
    name: "Signature Facial",
    description: "Deep cleansing facial for refreshed and glowing skin.",
    price: 899,
    duration: 60,
    img: "/images/services/signature-facial.jpg",
  },
  {
    id: 2,
    category: "Facial",
    name: "Diamond Peel",
    description: "Gentle exfoliation service for smoother skin texture.",
    price: 1299,
    duration: 75,
    img: "/images/services/diamond-peel.jpg",
  },
  {
    id: 3,
    category: "Brow",
    name: "Brow Care",
    description: "Brow shaping and grooming for a polished salon visit.",
    price: 349,
    duration: 30,
    img: "/images/services/brow-care.jpg",
  },
  {
    id: 4,
    category: "Aesthetic",
    name: "Pico Whitening Laser",
    description: "Brightening laser session for dark spots and uneven tone.",
    price: 1499,
    duration: 45,
    img: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=700&q=80",
  },
  {
    id: 5,
    category: "Hair",
    name: "Hair Rebond",
    description: "Smoothing hair treatment for a straighter polished finish.",
    price: 999,
    duration: 180,
    img: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=700&q=80",
  },
  {
    id: 6,
    category: "Nails",
    name: "Gel Manicure",
    description: "Clean nail care with long-wear gel polish.",
    price: 450,
    duration: 60,
    img: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=700&q=80",
  },
  {
    id: 7,
    category: "Spa",
    name: "Foot Spa with Massage",
    description: "Foot soak, scrub, and massage for relaxation.",
    price: 550,
    duration: 60,
    img: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=700&q=80",
  },
  {
    id: 8,
    category: "Lashes",
    name: "Classic Eyelash Extension",
    description: "Natural lash extension set for everyday definition.",
    price: 799,
    duration: 90,
    img: "https://images.unsplash.com/photo-1583001931096-959e9a1a6223?w=700&q=80",
  },
];

export const SALON_PACKAGES = [
  {
    id: 4,
    name: "Glow Up Package",
    description: "Pico Whitening Laser + Signature Facial",
    price: 2299,
    tag: "Best Seller",
    img: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=700&q=80",
    includes: ["Pico Whitening Laser", "Signature Facial", "Free Consultation"],
  },
  {
    id: 5,
    name: "Hair Rebond Premium",
    description: "Hair rebond with after-care treatment",
    price: 1999,
    tag: "Most Popular",
    img: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=700&q=80",
    includes: ["Hair Rebond", "Hair Mask", "Styling Finish"],
  },
  {
    id: 6,
    name: "Nails & Relax Bundle",
    description: "Gel Manicure + Foot Spa with Massage",
    price: 899,
    tag: "Great Value",
    img: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=700&q=80",
    includes: ["Gel Manicure", "Foot Spa", "Massage"],
  },
  {
    id: 8,
    name: "Full Beauty Day",
    description: "Facial + lashes + nail care",
    price: 2099,
    tag: "Premium",
    img: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=700&q=80",
    includes: ["Signature Facial", "Classic Eyelash Extension", "Gel Manicure"],
  },
];

export function formatServicePrice(price) {
  return `PHP ${Number(price || 0).toLocaleString()}`;
}
