// Current Happy Skin service menu and prices (2026).
const catalog = [
  ["Hair", "Hair Rebonding", 1500, 180],
  ["Hair", "Keratin Treatment", 1500, 150],
  ["Hair", "Hair Botox", 1800, 150],
  ["Hair", "Scalp Treatment", 799, 60],
  ["Spa & Body", "Body Scrub", 799, 60],
  ["Spa & Body", "Body Massage", 699, 60],
  ["Spa & Body", "Foot Massage", 399, 30],
  ["Spa & Body", "Body Slimming", 1200, 60],
  ["Spa & Body", "Body Contouring", 1200, 60],
  ["Lemon Bottle", "Face / Chin", 2000, 45],
  ["Lemon Bottle", "Arms", 3500, 60],
  ["Lemon Bottle", "Tummy", 4500, 60],
  ["Lemon Bottle", "Face + Arms + Tummy", 8500, 90],
  ["Aesthetic", "Body Whitening", 1500, 60],
  ["Nails", "Basic Manicure", 299, 40],
  ["Nails", "Gel Manicure", 499, 60],
  ["Nails", "Basic Pedicure", 499, 50],
  ["Nails", "Gel Pedicure", 599, 60],
  ["Nails", "Foot Spa", 250, 30],
  ["Nails", "Acrylic Nails", 1200, 90],
  ["Nails", "Gel Extension", 1000, 90],
  ["Nails", "Nail Art", 250, 30],
  ["Nails", "Nail Removal", 100, 20],
  ["Nails", "Nail Repair", 100, 20],
  ["Lash & Brow", "Lash Lift", 599, 60],
  ["Lash & Brow", "Classic Lash Extension", 999, 90],
  ["Lash & Brow", "Hybrid Lash Extension", 1299, 120],
  ["Lash & Brow", "Volume Lash Extension", 1499, 150],
  ["Lash & Brow", "Brow Shaping", 199, 20],
  ["Lash & Brow", "Brow Tint", 299, 30],
  ["Lash & Brow", "Brow Lamination", 699, 60],
  ["Hair", "Haircut", 250, 45],
  ["Hair", "Hair Spa", 699, 60],
  ["Hair", "Hair Treatment", 599, 60],
  ["Hair", "Hair Coloring", 1200, 120],
  ["Facial", "Basic Facial", 499, 60],
  ["Facial", "Deep Cleansing Facial", 599, 75],
  ["Facial", "Acne Facial", 799, 75],
  ["Facial", "Brightening Facial", 699, 60],
  ["Facial", "Anti-Aging Facial", 899, 75],
  ["Facial", "Hydrating Facial", 699, 60],
  ["Facial", "Signature Facial", 699, 60],
  ["Facial", "HydraFacial", 899, 75],
  ["Facial", "Diamond Peel", 599, 60],
  ["Facial", "LED Light Therapy", 399, 30],
  ["Aesthetic", "RF Facial", 799, 45],
  ["Aesthetic", "RF Body Contouring", 1200, 60],
  ["Aesthetic", "Cavitation", 1200, 60],
  ["Aesthetic", "HIFU Facial", 2500, 60],
  ["Aesthetic", "Skin Booster", 2500, 60],
  ["Aesthetic", "Microneedling", 1800, 60],
  ["Aesthetic", "Underarm Whitening", 699, 45],
  ["Aesthetic", "Bikini Whitening", 999, 45],
];

const serviceImages = {
  "Hair Rebonding": "hair-rebond",
  "Keratin Treatment": "hair-rebond",
  "Hair Botox": "hair-spa-treatment",
  "Scalp Treatment": "hair-spa-treatment",
  "Body Scrub": "swedish-body-massage",
  "Body Massage": "swedish-body-massage",
  "Foot Massage": "foot-spa-massage",
  "Body Slimming": "swedish-body-massage",
  "Body Contouring": "swedish-body-massage",
  "Face / Chin": "pico-whitening-laser",
  Arms: "underarm-whitening",
  Tummy: "underarm-whitening",
  "Face + Arms + Tummy": "underarm-whitening",
  "Body Whitening": "underarm-whitening",
  "Basic Manicure": "gel-manicure",
  "Gel Manicure": "gel-manicure",
  "Basic Pedicure": "classic-pedicure",
  "Gel Pedicure": "classic-pedicure",
  "Foot Spa": "foot-spa-massage",
  "Acrylic Nails": "gel-manicure",
  "Gel Extension": "gel-manicure",
  "Nail Art": "gel-manicure",
  "Nail Removal": "gel-manicure",
  "Nail Repair": "gel-manicure",
  "Lash Lift": "lash-lift-tint",
  "Classic Lash Extension": "classic-eyelash-extension",
  "Hybrid Lash Extension": "classic-eyelash-extension",
  "Volume Lash Extension": "classic-eyelash-extension",
  "Brow Shaping": "brow-care",
  "Brow Tint": "brow-care",
  "Brow Lamination": "brow-care",
  Haircut: "hair-rebond",
  "Hair Spa": "hair-spa-treatment",
  "Hair Treatment": "hair-spa-treatment",
  "Hair Coloring": "hair-spa-treatment",
  "Basic Facial": "signature-facial",
  "Deep Cleansing Facial": "signature-facial",
  "Acne Facial": "carbon-laser-facial",
  "Brightening Facial": "pico-whitening-laser",
  "Anti-Aging Facial": "signature-facial",
  "Hydrating Facial": "signature-facial",
  "Signature Facial": "signature-facial",
  HydraFacial: "signature-facial",
  "Diamond Peel": "diamond-peel",
  "LED Light Therapy": "carbon-laser-facial",
  "RF Facial": "carbon-laser-facial",
  "RF Body Contouring": "swedish-body-massage",
  Cavitation: "swedish-body-massage",
  "HIFU Facial": "carbon-laser-facial",
  "Skin Booster": "signature-facial",
  Microneedling: "carbon-laser-facial",
  "Underarm Whitening": "underarm-whitening",
  "Bikini Whitening": "underarm-whitening",
};

export const SALON_SERVICES = catalog.map(([category, name, price, duration], index) => ({
  id: index + 1,
  category,
  name,
  description: `${name} service at Happy Skin Salon.`,
  price,
  duration,
  img: `/images/services/generated/${serviceImages[name]}.jpg`,
}));

export const SALON_SERVICE_CATEGORIES = [
  "Facial",
  "Aesthetic",
  "Spa & Body",
  "Hair",
  "Nails",
  "Lash & Brow",
  "Lemon Bottle",
];

const serviceCategoryByName = new Map(SALON_SERVICES.map(({ name, category }) => [name, category]));

export function getSalonServiceCategory(name) {
  return serviceCategoryByName.get(name) || "Other";
}

export const SALON_PACKAGES = [];

export function formatServicePrice(price) {
  return `PHP ${Number(price || 0).toLocaleString()}`;
}
