"""add is_active to users

Revision ID: 1e1782292e82
Revises: h8i9j0k1l2m3
Create Date: 2026-08-08 00:50:03.814083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e1782292e82'
down_revision: Union[str, Sequence[str], None] = 'h8i9j0k1l2m3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_events_created_at'), 'auth_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_events_email'), 'auth_events', ['email'], unique=False)
    op.create_index(op.f('ix_auth_events_event_type'), 'auth_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_auth_events_id'), 'auth_events', ['id'], unique=False)
    op.create_index(op.f('ix_auth_events_user_id'), 'auth_events', ['user_id'], unique=False)
    op.alter_column('bookings', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('bookings', 'customer_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('bookings', 'branch_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('bookings', 'service_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_17605_branch_id'), table_name='bookings')
    op.drop_index(op.f('idx_17605_customer_id'), table_name='bookings')
    op.drop_index(op.f('idx_17605_ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('idx_17605_service_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_branch_date_status'), table_name='bookings')
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.drop_constraint(op.f('bookings_ibfk_1'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_ibfk_3'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_ibfk_2'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'branches', ['branch_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'services', ['service_id'], ['id'])
    op.alter_column('branches', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('branches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('branches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_17613_ix_branches_id'), table_name='branches')
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.alter_column('feedback', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('feedback', 'booking_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('feedback', 'customer_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('feedback', 'rating',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_17621_booking_id'), table_name='feedback')
    op.drop_index(op.f('idx_17621_customer_id'), table_name='feedback')
    op.drop_index(op.f('idx_17621_ix_feedback_id'), table_name='feedback')
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.drop_constraint(op.f('feedback_ibfk_2'), 'feedback', type_='foreignkey')
    op.drop_constraint(op.f('feedback_ibfk_1'), 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'users', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'bookings', ['booking_id'], ['id'])
    op.drop_index(op.f('ix_forecast_branch_date'), table_name='forecast_results')
    op.alter_column('inventory', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('inventory', 'branch_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('inventory', 'quantity',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('inventory', 'minimum_stock',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('inventory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('inventory', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_17629_ix_inventory_branch_id'), table_name='inventory')
    op.drop_index(op.f('idx_17629_ix_inventory_id'), table_name='inventory')
    op.create_index(op.f('ix_inventory_branch_id'), 'inventory', ['branch_id'], unique=False)
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.drop_constraint(op.f('inventory_ibfk_1'), 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'branches', ['branch_id'], ['id'])
    op.alter_column('services', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('services', 'duration_minutes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_17638_ix_services_id'), table_name='services')
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.alter_column('transactions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('transactions', 'booking_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('transactions', 'staff_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_17649_booking_id'), table_name='transactions')
    op.drop_index(op.f('idx_17649_ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('idx_17649_staff_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.drop_constraint(op.f('transactions_ibfk_2'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_ibfk_1'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['staff_id'], ['id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column(
        'users',
        sa.Column('session_version', sa.Integer(), nullable=False, server_default=sa.text('0')),
    )
    op.add_column('users', sa.Column('password_reset_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
    op.add_column(
        'users',
        sa.Column('password_reset_attempts', sa.Integer(), nullable=False, server_default=sa.text('0')),
    )
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'branch_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('users', 'verification_code_expires',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_17655_fk_users_branch_id_branches'), table_name='users')
    op.drop_index(op.f('idx_17655_ix_users_email'), table_name='users')
    op.drop_index(op.f('idx_17655_ix_users_id'), table_name='users')
    op.drop_index(op.f('idx_17655_oauth_id'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=True)
    op.drop_constraint(op.f('fk_users_branch_id_branches'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_branch_id_branches'), 'users', 'branches', ['branch_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('idx_17655_oauth_id'), 'users', ['oauth_id'], unique=True)
    op.create_index(op.f('idx_17655_ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('idx_17655_ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('idx_17655_fk_users_branch_id_branches'), 'users', ['branch_id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'verified_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'verification_code_expires',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'branch_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'password_reset_attempts')
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_code')
    op.drop_column('users', 'session_version')
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_ibfk_1'), 'transactions', 'bookings', ['booking_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key(op.f('transactions_ibfk_2'), 'transactions', 'users', ['staff_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.create_index(op.f('idx_17649_staff_id'), 'transactions', ['staff_id'], unique=False)
    op.create_index(op.f('idx_17649_ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('idx_17649_booking_id'), 'transactions', ['booking_id'], unique=False)
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('transactions', 'staff_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('transactions', 'booking_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('transactions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.create_index(op.f('idx_17638_ix_services_id'), 'services', ['id'], unique=False)
    op.alter_column('services', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('services', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('services', 'duration_minutes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('services', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_ibfk_1'), 'inventory', 'branches', ['branch_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_branch_id'), table_name='inventory')
    op.create_index(op.f('idx_17629_ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_index(op.f('idx_17629_ix_inventory_branch_id'), 'inventory', ['branch_id'], unique=False)
    op.alter_column('inventory', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('inventory', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('inventory', 'minimum_stock',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('inventory', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('inventory', 'branch_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('inventory', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_forecast_branch_date'), 'forecast_results', ['branch_id', 'forecast_date'], unique=False)
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key(op.f('feedback_ibfk_1'), 'feedback', 'bookings', ['booking_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key(op.f('feedback_ibfk_2'), 'feedback', 'users', ['customer_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.create_index(op.f('idx_17621_ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('idx_17621_customer_id'), 'feedback', ['customer_id'], unique=False)
    op.create_index(op.f('idx_17621_booking_id'), 'feedback', ['booking_id'], unique=False)
    op.alter_column('feedback', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('feedback', 'rating',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('feedback', 'customer_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('feedback', 'booking_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('feedback', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.create_index(op.f('idx_17613_ix_branches_id'), 'branches', ['id'], unique=False)
    op.alter_column('branches', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('branches', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('branches', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_ibfk_2'), 'bookings', 'users', ['customer_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key(op.f('bookings_ibfk_3'), 'bookings', 'services', ['service_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key(op.f('bookings_ibfk_1'), 'bookings', 'branches', ['branch_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.create_index(op.f('ix_bookings_branch_date_status'), 'bookings', ['branch_id', 'appointment_date', 'status'], unique=False)
    op.create_index(op.f('idx_17605_service_id'), 'bookings', ['service_id'], unique=False)
    op.create_index(op.f('idx_17605_ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('idx_17605_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('idx_17605_branch_id'), 'bookings', ['branch_id'], unique=False)
    op.alter_column('bookings', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bookings', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bookings', 'service_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('bookings', 'branch_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('bookings', 'customer_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('bookings', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_auth_events_user_id'), table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_id'), table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_event_type'), table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_email'), table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_created_at'), table_name='auth_events')
    op.drop_table('auth_events')
    # ### end Alembic commands ###
